name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"    # se ejecuta cada d√≠a a las 00:00 UTC
  workflow_dispatch:        # permite lanzarlo a mano desde Actions

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Generate snake animation
        uses: Platane/snk@v3
        with:
          github_user_name: YiouXia
          outputs: |
            output/github-contribution-grid-snake.svg
            output/github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: Commit and push snake files
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update snake animation"
          file_pattern: output/*.svg
